[gcp_service_account]
type = "service_account"
project_id = "ceu-da-boca-424618"
private_key_id = "c0f8f4c16a183817dcf0b941068ec11133074203"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDChKHm+gekIC5s
zE00+dnOnwEDbl6toDTSyUa2XWUJGoHcNlqbFFTQhRMvJDPF/Dz8k/yR4v5Lfc0/
nLMumQpzZAC0Zg4vf8bxHEl8tp+0GN0wY347A4Ue9iPt5ZzZVnN6GtICc3w/qXmU
v1El9HLL7tgqlZ+tViV4HyLJoC6Jwd9qcqnFUhayiB96KJAT3DuwwjZqaZRU9Slc
3R7i88hk/r85xKETShgeOW/3TM24gB86DvHamyL4mHhyEfHzLpSD947fDHxlbO8B
w6GUYtyBwryPhr4qut0vit9Ij2n9w2P9z238lqEOOpq5A4WrqFGoi8rOMKc995To
XsgOSL9lAgMBAAECggEANipr0R9XyF7Dvr0nVLSsb6p8REHUMIIXo4iz3a1lKKNO
fQ1PrrZ7JbOg03Q/zIaATw9Aejlc+ZWW9XtDtBqeu+IhhhqTIavxsIthdU5/a02v
Lj3OVU2WILiG6cSSKD04G8zjJRaWhz3AouihhrGq09n3LOiMVd7SwT/eVon525b5
VsCV/Nt2O/PwyY+z3BpkP4IylpHD9/xPF+w0OZF3KLGcZ2cJDYjV94vVKlDefM8H
07iFp22PUD/HsOSPwaqAZmyPD+Wliws3wjB5KIId5shGdyfaJQtZn5l6XtNay/QF
uhvHKfhQfVWfE3zNR9qmeXAweOBcp/wTEO9K9YZIMwKBgQD79TSiv8hmhCWY6paW
8DZCPp6sAHrq8IRLnErjPvyDrYz+G+m6LEuz1es/A82Wcdqaqf2UoNB2WpQMRVUh
2WkOVicv7SY+VX8ahldRAOUBYQE6hwmVKXFS0vA+caV0YrmFKMe6RiKUZtbEhCse
sWEj376CuW/370STBdh73hqyrwKBgQDFo4VgWfGXOE6cHU6bG1OKz2Vy6BCr6CTS
DMB+mSltt7Fs0tB3RnfmfW5zv9bSehJ4PisytU9xoEgNJCDCPO+D74DMaU0J8kN8
hbAtINFSkaRZBFNBRkhxpwqAEPxa6PHC2+HxQZEvifN9T5O0VrN3/XeGI5itVrLo
kIjBA54EKwKBgD4cqKkmViTPluUnj5AOD5ItFbiZNbQNLs/k66ExudZMRmGuR+QZ
X2Ap8CBMs7XOw3E1TsoBCuLiWXTc8quxiPB71JVABRmAwiCr1YKmkc3ROBhRic83
tDQSxB7grUUPwWRONU56U7P51iAD5Q1f9O5/Ddv0EuIwHduQqVl/210JAoGAUaJv
bxL3xVyOq9E3LL4mzclIwCO27yreOpzlzeT5xcYAVVDmpr3GvL/Gpazx0NJ3Wo9j
THizrd1kpXjsxw5gaIC/FK/SEG+vDHo0AQ/zJkXeOp6cvPOI7Njwb2GUuwBJDBHC
y+InVBmJJ5N9ERpW2xMpEZEWeVK8Z2977S3PUS0CgYBGB4Az24ghCfUfHlMSL+i/
uUmvKyie2uoYgh9fl3jwFqmhT/D0w+nY8qKnrzweCt/TdWqtTaoF1FAqnItFDznC
mize8YmuZS6ifTacIgfy1unvedm4D6OAb0YUVBEI3qoiVkvrwMoVTDA8Zc1Er1vT
2mTVEziOZJE7NsYoSUaGKA==
-----END PRIVATE KEY-----"""
client_email = "ceu-da-boca@ceu-da-boca-424618.iam.gserviceaccount.com"
client_id = "101684175780054280619"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ceu-da-boca%40ceu-da-boca-424618.iam.gserviceaccount.com"
